language: c
sudo : required
dist : trusty

matrix:
  include:
    - os : linux
      compiler : gcc
      addons:
    - os : osx

addons:
  apt:
    packages:
    - cmake

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install ocl-icd-opencl-dev libsdl2-dev gnustep-devel libzip-dev mesa-common-dev opencl-headers -y

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest -VV
